# Generated by Django 3.2.5 on 2021-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_to',
            field=models.BooleanField(default=False),
        ),
    ]
